modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory
issueTrackerURL="https://github.com/CJ-MC-Mods/Overloaded/issues"
license="All rights reserved"
[[mods]]
    modId="overloaded"
    namespace="overloaded"
    version="${mod_version}"
    displayName="Overloaded"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/overloaded"
    logoFile="logo.png"
    credits="Assets: Mega___Byte | Documentation / Thinkers: Sironin, Braingkk"
    authors="CJ Miller (cjm721)"
    description='''
    Adds various complicated and tedious things that will minimize your need to destroy your server with your chunk sized arrays of machines.

    Almost all balance values can be configured.
    '''
#    [[dependencies.overloaded]] #optional
#        modId="neoforge" #mandatory
#        type="required" #mandatory
#        versionRange="${neo_version_range}" #mandatory
#        ordering="NONE"
#        side="BOTH"
#    [[dependencies.overloaded]]
#        modId="minecraft"
#        type="required"
#        # This version range declares a minimum of the current minecraft version up to but not including the next major version
#        versionRange="${minecraft_version_range}"
#        ordering="NONE"
#        side="BOTH"
